language: perl
perl:
  - '5.8'
  - '5.8.7'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - 'blead'
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/travis-perl-helpers
  - source ~perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lv $(test-dirs)
after_success:
  - coverage-report
